[package]
name = "p2p-messengerr"
version = "0.1.0"
authors = ["gui"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
